baseURL = "https://mp2i-france.github.io/mp2i-france-website/"
title = "Prépas MP2I"
theme = "PaperMod"
defaultContentLanguage = "fr"
copyright = "MP2I — All rights reserved."
paginate = 4
googleAnalytics = "G-BW19BY0LKC"  # add your tracking id
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  '/' = '/:filename/'

[params]
  env = "production"  # to enable google analytics, opengraph, twitter-cards and schema.
  keywords = ["MP2I", "PaperMod", "Prépa"]
  description = "Site des classes préparatoires MP2I"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  defaultTheme = "light"  # dark, light
  ShowReadingTime = true

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/mp2i-france/mp2i-france-website"

  [[params.socialIcons]]
    name = "discord"
    url = "https://discord.gg/w4ugrWy84W"

[languages]
  [languages.fr]
    languageName = "French"
    weight = 1

    [languages.fr.homeInfoParams]
      Title = "Bienvenue sur le site des MP2I👋"
      Content = """Ce site web est conçu par des étudiants en classes 
      préparatoires MP2I, il vise une présentation qualitative de 
      cette nouvelle filière."""

[markup]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "La filière"
    url = "/posts/mp2i/"
    weight = 1
  
  [[menu.main]]
    name = "Admission"
    url = "/posts/admission/"
    weight = 2
  
  [[menu.main]]
    name = "Ressources"
    url = "/posts/ressources/"
    weight = 3

  [[menu.main]]
    name = "Qui sommes-nous?"
    url = "/posts/contact/"
    weight = 4

  [[menu.main]]
    name = "Recherche"
    url = "/recherche/"
    weight = 5
