baseURL = "https://mp2i-france.github.io/mp2i-france-website/"
title = "Prépas MP2I"
theme = "LoveIt"
defaultContentLanguage = "fr"
googleAnalytics = "G-BW19BY0LKC"  # add your tracking id
enableRobotsTXT = true

[params]
  version = "0.2.X"
  description = "Site des classes préparatoires MP2I"
  keywords = ["Theme", "Hugo"]
  defaultTheme = "auto"
  gitRepo = "https://github.com/mp2i-france/mp2i-france-website"
  dateFormat = "02/01/2006 "

  [params.app]
    title = "Prépas MP2I"
    noFavicon = false
    themeColor = "#ffffff"
    iconColor = "#5bbad5"
    tileColor = "#da532c"

  [params.search]
    enable = true
    type = "lunr"
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"

    [params.header.title]
      logo = "/images/logo.png"
      name = "Prépas MP2I"
      # add extra information before the name (HTML supported), such as icons
      pre = ""
      typeit = true  # whether to use typeit animation for title name

  [params.footer]
    enable = true
    hugo = false
    copyright = true
    author = true
    since = 2021
    license = """<a rel="license external nofollow noopener noreffer"
    href="https://creativecommons.org/licenses/by-nc/4.0/" 
    target="_blank">CC BY-NC 4.0</a>"""

  [params.section]
    paginate = 4
    dateFormat = "01-02"

  [params.list]
    paginate = 4
    dateFormat = "01-02"

  [params.home]
    [params.home.profile]
      enable = true
      avatarURL = "/images/logo.png"
      title = "Prépas MP2I"
      subtitle = "Bienvenue sur le site des classes préparatoires MP2I !"
      typeit = true
      social = true
      disclaimer = ""

    [params.home.posts]
      enable = true
      paginate = 4

  [params.social]
    GitHub = "mp2i-france/mp2i-france-website"
    Email = "mp2i@protonmail.com"

  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = true

    [params.page.share]
      enable = true
      Facebook = true

  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = ""
      anonymizeIP = true

  [params.cookieconsent]
    enable = true
    # text strings used for Cookie consent banner
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""

[markup]
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

    [markup.goldmark.renderer]
      unsafe = true

[author]
  name = "MP2I"
  email = "mp2i@protonmail.com"

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true

[Permalinks]
  posts = ":filename"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]

[menu]
  [[menu.main]]
    name = "La filière"
    url = "mp2i/"
    weight = 1
  
  [[menu.main]]
    name = "Admission"
    url = "admission/"
    weight = 2
  
  [[menu.main]]
    name = "Ressources"
    url = "ressources/"
    weight = 3

  [[menu.main]]
    name = "Qui sommes-nous?"
    url = "contact/"
    weight = 4
