baseURL = "https://mp2i-france.github.io/mp2i-france-website/"
title = "Prépas MP2I"
theme = "slick"
copyright = "MP2I — All rights reserved."

languageCode = "fr-FR"
enableEmoji = true
googleAnalytics = "G-BW19BY0LKC"  # add your tracking id
enableRobotsTXT = true
canonifyURLs = true

[params]
  subtitle = "Site des classes préparatoires MP2I"
  description = "Site des classes préparatoires MP2I"
  favicon = "favicon.ico"  # path to a .ico to use as favicon

  showNavHeader = true
  showMeta = true

[permalinks]
  '/' = '/:filename/'

[menu]
  [[menu.main]]
    name = "La filière"
    url = "/mp2i"
    weight = 1
  
  [[menu.main]]
    name = "Admission"
    url = "/admission"
    weight = 2
  
  [[menu.main]]
    name = "Ressources"
    url = "/ressources"
    weight = 3

  [[menu.main]]
    name = "Qui sommes-nous?"
    url = "/contact"
    weight = 4

  [[menu.footer]]
    name = "GitHub"
    title = "MP2I France"
    url = "https://github.com/mp2i-france/mp2i-france-website/"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true                   # Allow html (needed for some shortcodes)
